# Generated by Django 4.0.4 on 2022-05-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carro',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carroproduto',
            name='avaliacao',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carroproduto',
            name='quantidade',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='carroproduto',
            name='subtotal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='desconto',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='subtotal',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='pedido_order',
            name='total',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_mercado',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='produto',
            name='visualizacao',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
