# Generated by Django 4.0.4 on 2022-05-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0002_alter_carro_total_alter_carroproduto_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_completo',
            field=models.BooleanField(blank=True, default=False, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pedido_order',
            name='pagamento_method',
            field=models.CharField(choices=[('Dinheiro Entrega', 'Dinheiro Entrega'), ('khalti', 'khalti')], default='Dinheiro Entrega', max_length=20),
        ),
    ]
